image: node:latest

cache:
  paths:
    - node_modules

stages:
  - 'prepare'
  - 'lint'

install:
  stage: 'prepare'
  script:
    - npm i
    - npx --no-install @ranwawa/branchlint

lint:branch:
  stage: 'lint'
  script:
    - npx @ranwawa/branchlint

lint:message:
  stage: 'lint'
  script:
    - npx --no-install @ranwawa/branchlint
