image: node:latest

cache:
  paths:
    - node_modules

stages:
  - 'prepare'
  - 'lint'

#install:
#  stage: 'prepare'
#  script: npm ci

lint:branch:
  stage: 'lint'
  script:
    - echo $CI_COMMIT_BRANCH $CI_COMMIT_REF_NAME
    - npm install
    - npx @ranwawa/branchlint
#lint:message:
#  stage: 'lint'
#  script:
#    - echo lint:branch
#    - npx --no-install @ranwawa/branchlint
