image: node:latest

cache:
  paths:
    - node_modules

variables:
  COMMON_ANCESTOR: $(git merge-base origin/master HEAD)

stages:
  - 'prepare'
  - 'lint'

install:
  stage: 'prepare'
  script:
    - echo $COMMON_ANCESTOR
    - npm i
    - npx --no-install @ranwawa/branchlint

lint:branch:
  stage: 'lint'
  script:
    - npx @ranwawa/branchlint

lint:message:
  stage: 'lint'
  script:
    - npx --no-install @ranwawa/branchlint
