image: node:latest

cache:
  paths:
    - node_modules

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  #- 'prepare'
  #- 'lint'
  - 'test'

# install:
#   stage: 'prepare'
#   script: npm ci

# lint:branch:
#   stage: 'lint'
#   script:
#     - npx --no-install @ranwawa/branchlint

# lint:tree:
#   stage: 'lint'
#   script:
#     - npx --no-install @ranwawa/treelint
# lint:message:
#   stage: 'lint'
#   script:
#     - npx --no-install @ranwawa/branchlint

code_quality:
  services:
  tags:
    - cq-sans-dind
  artifacts:
    paths: [gl-code-quality-report.json]
