image: node:latest

stages:
  - 'lint'

lint:branch:
  stage: 'lint'
  script:
    - echo lint:branch
    - npx --no-install @ranwawa/branchlint

lint:message:
  stage: 'lint'
  script:
    - echo lint:branch
    - npx --no-install @ranwawa/branchlint
