#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMON_ANCESTOR=$(git merge-base origin/master HEAD)
FILES=$(git diff --name-only --diff-filter=d 7d0c8a2b0c26942dec8464024913faec4b9a6942..HEAD)

echo '当前分支与origin/master的共同祖先节点:'$COMMON_ANCESTOR
echo $FILES

# TODO 怎么把参数传进来
function getFiles() {
	declare -a list=()
	for p in $FILES
	do 
	  case $p in
		  *.scss|*.css|*.vue)
			list=(${list[@]} $p)
			;;
		  *)
			;;
		esac
	done
	echo ${list[*]}
}

function getScriptFiles() {
	declare -a list=()
	for p in $FILES
	do 
	  case $p in
		  *.js|*.jsx|*.ts|*.tsx|*.vue|*.mjs)
			list=(${list[@]} $p)
			;;
		  *)
			;;
		esac
	done
	echo ${list[*]}
}

# lint:branch todo
# lint:file-structrue todo

# lint:message
echo '------检测commit message信息...------'
npx --no-install commitlint --from $COMMON_ANCESTOR

# lint:script
echo '------检测脚本代码------'
npx --no-install eslint $(getScriptFiles)

# lint:style
echo '------检测样式代码------'
npx --no-install stylelint --allow-empty-input $(getFiles)


# lint:prettier
echo '------检测代码风格------'
npx --no-install prettier --check --ignore-unknown $FILES
