#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMON_ANCESTOR=$(git merge-base origin/master HEAD)
FILES=$(git diff --name-only --diff-filter=d 7d0c8a2b0c26942dec8464024913faec4b9a6942..HEAD)

echo '当前分支与origin/master的共同祖先节点:'$COMMON_ANCESTOR

# TODO 怎么把参数传进来
function getFiles() {
	declare -a list=()
	for p in $FILES
	do 
	  case $p in
		  *.scss|*.css|*.vue)
			list=(${list[@]} $p)
			;;
		  *)
			;;
		esac
	done
	echo ${list[*]}
}

function getScriptFiles() {
	declare -a list=()
	for p in $FILES
	do 
	  case $p in
		  *.js|*.jsx|*.ts|*.tsx|*.vue|*.mjs)
			list=(${list[@]} $p)
			;;
		  *)
			;;
		esac
	done
	echo ${list[*]}
}

# lint:branch
echo '------lint:branch...------'
npx --no-install @ranwawa/branchlint

# lint:file-structrue TODO

# lint:message
echo '------lint:message...------'
npx --no-install commitlint --from $COMMON_ANCESTOR

# lint:script
echo '------lint:script...------'
npx --no-install eslint $(getScriptFiles)

# lint:style
echo '------lint:style...------'
# TODO 可以使用忽略除指定后缀以外的文件的格式
if [ -n ${getFiles}'' ]; then
  npx --no-install stylelint --allow-empty-input ${getFiles}
fi


# lint:prettier
echo '------lint:prettier...------'
npx --no-install prettier --check --ignore-unknown $FILES
